import { StyleSheet } from 'react-native';
import { Dimensions } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fbfcfb',
  },
  somecontainer: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#fbfcfb',
  },
  welcome: {
    fontSize: 46,
    textAlign: 'center',
    color: 'black',
    marginTop: 70,
    margin: 20,
  },
  instructions: {
    fontSize: 14,
    textAlign: 'center',
    color: 'black',
    marginTop: 50,
    margin: 10,
  },
  onlinetext: {
    fontSize: 14,
    textAlign: 'center',
    color: 'black',
    marginTop: 20,
    margin: 10,
  },
  pdfcontainer: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: 25,
  },
  pdf: {
    flex: 1,
    width: Dimensions.get('window').width,
  },
  bottom: {
    flex: 1,
    justifyContent: 'flex-end',
    marginBottom: 12
  },
  header: {
    flex: 1,
  },
  food: {
    textAlign: 'center',
    fontWeight: 'bold',
    color: 'black'
  },
  spektrumbutton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 50,
    backgroundColor: '#FF60A5',
    borderRadius: 50,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    elevation: 2,
    margin: 10,
  },
  spektrumimagestyle: {
    alignItems: 'center',
    width: 53,
    height: 53,
  },
  spektrakelbutton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 50,
    backgroundColor: '#24890d',
    borderRadius: 50,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    elevation: 2,
    margin: 10,
  },
  instagrambutton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 50,
    backgroundColor: '#3f729b',
    borderRadius: 50,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    elevation: 2,
    margin: 10,
  },
  facebookbutton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 50,
    backgroundColor: '#fff',
    borderRadius: 50,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    elevation: 2,
    margin: 10,
  },
})